version: 0.2
env:
  variables:
    CONFORMITY_API_BASE: "https://conformity.us-1.cloudone.trendmicro.com/api"
    TEMPLATE_FILE: "template-insecure.yaml"  # CONFIRM this filename exists
  secrets-manager:
    CC_API_KEY: "conformity/apiKey"  # REMOVED :ApiKey suffix if not in Secrets Manager

phases:
  install:
    commands:
      - yum -y install jq curl

  build:
    commands:
      - echo "Validating files..."
      - ls -la
      - if [ ! -f "$TEMPLATE_FILE" ]; then echo "ERROR: Template missing!"; exit 1; fi

      - echo "Starting scan..."
      - |
        set -e  # Exit immediately on errors
        CONTENTS=$(jq -MRs '.' < "$TEMPLATE_FILE")
        PAYLOAD="{\"data\":{\"attributes\":{\"type\":\"cloudformation-template\",\"contents\":${CONTENTS}}}}"
        
        RESP=$(curl -f -s -X POST \
          -H "Authorization: ApiKey ${CC_API_KEY}" \
          -H "Content-Type: application/vnd.api+json" \
          "${CONFORMITY_API_BASE}/template-scanner/scan" \
          --data-binary "$PAYLOAD")
        
        echo "$RESP" | jq . > scan.json
        if [ ! -s scan.json ]; then echo "Empty scan results!"; exit 1; fi

artifacts:
  files:
    - scan.json