AWSTemplateFormatVersion: "2010-09-09"
Description: Demo S3 bucket (insecure)
Resources:
  DemoBucket:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      # Missing encryption & secure transport policy